### ISSUE TITLE
p49 好像有个bug

### ISSUE THREAD

**Issue by L30Yu** [jslaobi/jslaobi-leetcode-js#1]
首先非常感谢你做的视频。

Input
["bdddddddddd", "bbbbbbbbbbc"]
Output
[["bdddddddddd","bbbbbbbbbbc"]]
Expected
[["bbbbbbbbbbc"],["bdddddddddd"]]

原因是line 13 https://github.com/jslaobi/jslaobi-leetcode-js/blob/master/0049.GroupAnagrams.js#L13
如果只是直接join，可能造成不同值，出现相同的key，比如都出现了10次，直接join后就看不出差别了
[
  0, 1, 0, 10, 0, 0, 0, 0,
  0, 0, 0,  0, 0, 0, 0, 0,
  0, 0, 0,  0, 0, 0, 0, 0,
  0, 0
]
[
  0, 10, 1, 0, 0, 0, 0, 0,
  0,  0, 0, 0, 0, 0, 0, 0,
  0,  0, 0, 0, 0, 0, 0, 0,
  0,  0
]

随便加个空格或者其他字符做分割应该可以保证唯一性

**Comment by quanquan97** [comment]
我正好奇呢  想半天  非常感谢你的解答！！！

**Comment by jslaobi** [comment]
已修复并在注释中表示感谢！

**Comment by friedRawFish** [comment]
万分感谢！！！
